FROM ubuntu:15.10
MAINTAINER Norio Nomura <norio.nomura@gmail.com>

# Install Dependencies

RUN apt-get update && \
    apt-get install -y \
      build-essential \
      clang \
      git \
      libedit-dev \
      libicu-dev \
      libxml2-dev \
      python2.7 \
      python2.7-dev \
      wget \
      && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
