FROM ubuntu:14.04
MAINTAINER Norio Nomura <norio.nomura@gmail.com>

# Install Dependencies

RUN apt-get update && \
    apt-get install -y \
      autoconf \
      build-essential \
      clang-3.5 \
      git \
      icu-devtools \
      libblocksruntime-dev \
      libbsd-dev \
      libedit-dev \
      libicu-dev \
      libkqueue-dev \
      libncurses5-dev \
      libpython-dev \
      libsqlite3-dev \
      libtool \
      libxml2-dev \
      ninja-build \
      pkg-config \
      python \
      swig \
      systemtap-sdt-dev \
      uuid-dev \
      wget \
      && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.5 100 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.5 100 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Build and Install CMake
RUN export CMAKE_VERSION="3.6.1" && \
    wget https://cmake.org/files/v3.6/cmake-${CMAKE_VERSION}.tar.gz && \
    tar zxf cmake-${CMAKE_VERSION}.tar.gz && \
    cd cmake-${CMAKE_VERSION} && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf cmake-${CMAKE_VERSION}
